<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="index.xsl"?>

<!DOCTYPE CV [
    <!ELEMENT CV (Name, Age, Email, Phone, PostSecondaryEducation, University, PTWorkDone, skills)>
    <!ELEMENT Name (#PCDATA)>
    <!ELEMENT Age (#PCDATA)>
    <!ELEMENT Email (#PCDATA)>
    <!ELEMENT Phone (#PCDATA)>
    <!ELEMENT PostSecondaryEducation (#PCDATA)>
    <!ELEMENT University (#PCDATA)>
    <!ELEMENT PTWorkDone (#PCDATA)>
    <!ELEMENT skills (#PCDATA)>
]>

<CV>
    <Name>Mazin Sherif</Name>
    <Age>19</Age>
    <Email>mazin.sherif@gmail.com</Email>
    <Phone>+971569330647</Phone>
    <PostSecondaryEducation>Graduated from India, Sree Gokulam Public School</PostSecondaryEducation>
    <University>Current student at UOWD pursuing Computer Science</University>
    <PTWorkDone>Marketing promoter at BYJU's, Par-time IT technician at IP Technics</PTWorkDone>
    <skills>Logitech E-sports player, District football player during high school</skills>
</CV>     